### PR TITLE
fix: wait for SerialAPIStarted message after soft reset, poll controller if it doesn't come

### PR DESCRIPTION
**Pull request by AlCalzone**
Hopefully this makes the soft reset production ready.

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

**Comment by blhoward2** [comment]
Seems to work fine.

HUBZB-1:
```
14:09:41.486 DRIVER   opening serial port /dev/ttyUSB0
14:09:41.504 DRIVER   serial port opened
14:09:41.507 SERIAL » [NAK]                                                                   (0x15)
14:09:41.513 CNTRLR   Performing soft reset...
14:09:41.636 SERIAL » 0x01030008f4                                                         (5 bytes)
14:09:41.640 DRIVER » [REQ] [SoftReset]
14:09:41.648 SERIAL « [ACK]                                                                   (0x06)
14:09:41.662 CNTRLR   Waiting for the controller to reconnect...
14:09:43.168 CNTRLR   Waiting for the Serial API to start...
14:09:48.176 CNTRLR   Did not receive notification that Serial API has started, checking if it respo
                      nds...
14:09:48.201 SERIAL » 0x01030015e9                                                         (5 bytes)
14:09:48.203 DRIVER » [REQ] [GetControllerVersion]
14:09:48.209 SERIAL « [ACK]                                                                   (0x06)
14:09:48.217 SERIAL « 0x011001155a2d5761766520342e3035000197                              (18 bytes)
14:09:48.220 SERIAL » [ACK]                                                                   (0x06)
14:09:48.224 DRIVER « [RES] [GetControllerVersion]
                        payload: 0x5a2d5761766520342e30350001
14:09:48.237 CNTRLR   Serial API responded
14:09:48.242 DRIVER   loading configuration...
```

Z-Pi 7
```
14:10:57.132 CNTRLR   Performing soft reset...
14:10:57.140 SERIAL » 0x01030008f4                                                         (5 bytes)
14:10:57.142 DRIVER » [REQ] [SoftReset]
14:10:57.145 SERIAL « [ACK]                                                                   (0x06)
14:10:57.150 CNTRLR   Waiting for the controller to reconnect...
2021-10-24 14:10:57.160 INFO APP: GET /api/auth-enabled 304 2.503 ms - -
14:10:58.307 SERIAL « 0x0109000a030001020100fd                                            (11 bytes)
14:10:58.310 SERIAL » [ACK]                                                                   (0x06)
14:10:58.314 DRIVER « [REQ] [SerialAPIStarted]
                        payload: 0x030001020100
14:10:58.325 CNTRLR   reconnected and restarted
14:10:58.331 DRIVER   loading configuration...
```

**Review by blhoward2 — APPROVED** [review]

**Comment by AlCalzone** [comment]
@robertsLando confirmed this to be working for his wonky stick too 👍🏻

**Comment by robertsLando** [comment]
Well done @AlCalzone 💪🏼

**Pull request merged**
