### PR TITLE
fix: show status for FGS223

### PR DESCRIPTION
**Pull request by jbenc**
Fibaro FGS223 needs the same workaround as FGS222. Tested successfully with
the device.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Interesting, I've never had any issues reported for this device.

Just to be sure, can you re-interview your device, then control it with a switch and post a driver log of both? Loglevel debug please, attach file by dragging and dropping.

**Comment by jbenc** [comment]
I've got the log but I am not comfortable sharing it publicly with my device ids present. Do you have a tool to anonymize the log before attaching it here? Or can I share it privately only?

**Comment by AlCalzone** [comment]
You can send it to the email adress in my profile.

**Comment by AlCalzone** [comment]
Actually, I just noticed I have that device and it works flawlessly in its current configuration. Firmware 3.2 with this lifeline association:
Source: Endpoint 0, Group: 1, Target: Node 1, Target Endpoint: 0

**Comment by jbenc** [comment]
Maybe it's something in the newer firmware? My device has 3.3. But that's hard to verify. All I'm able to say is without the workaround, currentValue for the first switch is not recognized, with the workaround, it is.

Did you receive the log I sent you? Anything interesting in there?

**Comment by AlCalzone** [comment]
> Did you receive the log I sent you?

I didn't spot any email regarding this. Can you try again?

**Comment by AlCalzone** [comment]
I got it now. You might want to update the driver to something more recent (>= 8.5.0) before doing any further tests. Yours is still on 8.1.1.

I'm relatively certain that a re-interview on 8.5.0 or later fixes things for you.

**Comment by AlCalzone** [comment]
Ok I take it back. 8.5.0 does also not work correctly. The main issue is that association group 1 on the root needs a multi channel association, but gets assigned a normal association.

**Comment by AlCalzone** [comment]
The correct fix is in #3597

```
2021-10-26T16:13:42.718Z CNTRLR   [Node 009] [~] [Meter] value[66049]: 10.4 => 0                    [Endpoint 2]

2021-10-26T16:13:42.720Z SERIAL » [ACK]                                                                   (0x06)

2021-10-26T16:13:42.724Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      2
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:       Electric
                                        scale:      W
                                        rate type:  Consumed
                                        value:      0
                                        time delta: 0 seconds

2021-10-26T16:13:44.711Z SERIAL « 0x0112000400090c600d01003202213200000000a3                          (20 bytes)

2021-10-26T16:13:44.715Z CNTRLR   [Node 009] [~] [Meter] value[66049]: 0 => 0                       [Endpoint 1]

2021-10-26T16:13:44.716Z SERIAL » [ACK]                                                                   (0x06)

2021-10-26T16:13:44.719Z DRIVER « [Node 009] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      1
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:       Electric
                                        scale:      W
                                        rate type:  Consumed
                                        value:      0
                                        time delta: 0 seconds
```

**Comment by jbenc** [comment]
I confirm that #3597 works, thanks a lot for your help!

**Pull request closed without merging**
