### PR TITLE
refactor: reverse functionality of soft reset env var, enable by default

### PR DESCRIPTION
**Pull request by blhoward2**
After further testing, it appears the docker issue is largely a non-issue. This PR enables soft reset on startup by default and reverses the functionality of the environment variable.

@robertslando this will require a change to the UI too.

### CODE REVIEW

**Comment by blhoward2** [comment]
@robertsLando @AlCalzone asked if you could test this since you'd had some issues before. One thing to note, enableSoftReset should be set to true by default now, but zwavejs2mqtt still says its disabled if I have the setting set to Auto. It works if I set it to enabled. Is there a bug in the UI?

**Comment by AlCalzone** [comment]
This seems to work fine for me, so if the feature stays disabled, the bug must be in z2m.

**Comment by blhoward2** [comment]
I think it's because Auto sets null, but I'm not sure.

**Comment by AlCalzone** [comment]
That might be. @robertsLando `null` is never a good default choice for zwave-js's config options. It only overrides `undefined` with the default.

**Review by AlCalzone — APPROVED** [review]

**Comment by robertsLando** [comment]
Sorry missed this

**Pull request merged**
